version: '3'

services:

  redis:
    image: redis:alpine
    restart: always
    networks:
      - authelia-backend

  mongo:
    image: mongo:3
    restart: always
    ports:
      - 27017:27017/tcp
    volumes:
      - mongodb:/data/db/
      # - ../../../data/authelia/mongo-db/:/data/db/
    networks:
      - authelia-backend

  smtp:
    image: tophfr/mailcatcher
    ports:
      - 8085:80
    networks:
      - authelia-backend

  authelia:
    image: clems4ever/authelia:latest
    restart: always
    depends_on:
    - redis
    environment:
      NODE_TLS_REJECT_UNAUTHORIZED: '0'
    volumes:
      - ./config/authelia-config.yml:/etc/authelia/config.yml:ro
    networks:
      - authelia-backend
      - authelia-frontend
      - ldap

  nginx-authelia:
    image: nginx:alpine
    restart: always
    expose:
      - '80'
    volumes:
      - ./config/nginx-authelia.conf:/etc/nginx/conf.d/default.conf
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
    env_file:
      - .letsencrypt.env
    networks:
      - authelia-frontend
      - webproxy

volumes:
  mongodb:

networks:
  authelia-backend:
  authelia-frontend:
  ldap:
    external:
      name: ${LDAP_NETWORK}
  webproxy:
    external:
      name: ${PROXY_NETWORK}
